export const FETCH_AUTH = 'FETCH_AUTH';
export const FETCH_ACCESS_TOKEN = 'FETCH_ACCESS_TOKEN';

export const FETCH_AUTH_SUCCESS = 'FETCH_AUTH_SUCCESS';
export const FETCH_AUTH_ERROR = 'FETCH_AUTH_ERROR';
export const LOADING = 'LOADING';
